#运行环境配置文件
server:
  servlet:
    context-path: /cms
    session:
      timeout: 1440s
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
serverproperties:
  port_num: 8080
  filePath: /www/cmsfile/
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: true
    check-template: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.25/db_imis2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: imis2
    password: 2015imis2

  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  #resources:
  #  static-locations: classpath:/templates/
debug: false