#开发环境配置文件
server:
  servlet:
    context-path: /cms
    session:
      timeout: 1440s
  port: 8080
serverproperties:
  port_num: 8080
  filePath: F:\JAVA Workspace\Temp\
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_imis2?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: 
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb


  #resources:
  #  static-locations: classpath:/templates/
debug: true
