#开发环境配置文件
server:
  servlet:
    context-path: /cms
  port: 8080
serverproperties:
  port_num: 8080
  filePath: F:\JAVA Workspace\Temp\
  zipfilePath: F:\JAVA Workspace\Temp\zip\
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_imis2?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: imis2
    password: 2015imis2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #resources:
  #  static-locations: classpath:/templates/
debug: true

