#运行环境配置文件
server:
  servlet:
    context-path: /cms
  port: 8081
serverproperties:
  port_num: 8081
  filePath: /www/cmsfile/
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_imis2?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: imis2
    password: 2015imis2

  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  #resources:
  #  static-locations: classpath:/templates/
debug: false

