#开发环境配置文件
server:
  servlet:
    context-path: /cms
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_imis2?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: imis2
    password: 2015imis2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
debug: true